models:
  - name: user_id_stitcher
    model_type: id_stitcher
    model_spec:
      entity_key: user
      edge_sources:
        - from: inputs/crm
        - from: inputs/funraisin
        - from: inputs/jumbo
        - from: inputs/patient

var_groups:
  - name: default_vars
    entity_key: user
    vars:
      - entity_var:
          name: crm_all_ids
          select: array_agg(distinct contact_id)
          from: inputs/crm
      - entity_var:
          name: funraisin_all_ids
          select: array_agg(distinct contact_id)
          from: inputs/funraisin
      - entity_var:
          name: jumbo_all_ids
          select: array_agg(distinct contact_id)
          from: inputs/jumbo
      - entity_var:
          name: patient_all_ids
          select: array_agg(distinct contact_id)
          from: inputs/patient
      - entity_var:
          name: first_name
          select: first_value(first_name)
          from: inputs/crm
      - entity_var:
          name: last_name
          select: first_value(last_name)
          from: inputs/crm
